### ISSUE TITLE
Phalcon MVC giving error

### ISSUE THREAD

**Issue by CeRBeR666** [EdwinHoksberg/php-fcm#1]
Greetings,
your class really is very simple and clean. Thank you so much.
I wanted to use phalcon framework. But when I create an autoload with composer, I do not get the namespace of the class.
I've tried all the options.
`
namespace Vokuro\Controllers;
use Phalcon\Tag; 
use Phalcon\Mvc\Model\Criteria;
use Phalcon\Paginator\Adapter\Model as Paginator;
use Vokuro\Models\Aksiyonlar;
use Vokuro\Models\Atamalar;
use Vokuro\Models\Users;
use Vokuro\Models\Yorumlar;
use Vokuro\Models\Dosyalar;
use Vokuro\Models\Push;
use FcmClient;
`

`
$client = new \FcmClient('AAAAWtYCPEM...', '390..');
$notification = $client->pushNotification('The title', 'The body', $kayit['push_user_key']);
$response = $client->send($notification);
`

Can you help me ?

**Comment by EdwinHoksberg** [comment]
Hi,

You should be able to use the class like this:

```php
use Fcm\FcmClient;

$client = FcmClient::create('123', 'bla');
```
or
```php
$client = \Fcm\FcmClient::create('123', 'bla');
```

Please look at the documentation for more examples: https://php-fcm.readthedocs.io/en/latest/

**Comment by CeRBeR666** [comment]
Hi,
Thank you for interesting. It's my bad. My composer files corrupted. Now it fixed. Everything working. Thank you.
