### ISSUE TITLE
Response messages

### ISSUE THREAD

**Issue by rolinger** [EdwinHoksberg/php-fcm#10]
When I send a notification that has an error I get something like the below - obviously, the notification does not arrive to my phone:

```
    $client = new \Fcm\FcmClient($serverKey,$senderID) ;
    $notification = new \Fcm\Push\Notification();
    
    $notification
        ->addRecipient('/topic/' .$topicID)
        ->setTitle($sub)
        ->setBody($msg)
        ->setSound("default")
        ->setColor("blue");
```
In the above, `/topic/` should be `/topics/` - thus it will error out with the below:
```
array(5) {
  'multicast_id' =>
  int(9014353506250345342)
  'success' =>
  int(0)
  'failure' =>
  int(1)
  'canonical_ids' =>
  int(0)
  'results' =>
  array(1) {
    [0] =>
    array(1) {
      'error' =>
      string(19) "InvalidRegistration"
    }
  }
}
```

However, when I  send a notification that is successful:

```
    $client = new \Fcm\FcmClient($serverKey,$senderID) ;
    $notification = new \Fcm\Push\Notification();
    
    $notification
        ->addRecipient('/topics/' .$topicID)
        ->setTitle($sub)
        ->setBody($msg)
        ->setSound("default")
        ->setColor("blue");
```
I do get the notification to my phone.  And correctly sent, I only get the following:
```
array(1) {
    'message_id' =>
    int(154231004164960%c5f39c08c5f39c543)
  }
```

It seems the documentation is off...and the "success" message does not have all the other intricate data that a failed message has.  I have tried multiple combinations of failures and successes - and each time the success just has the `message_id`.  In the docs it shows a `success => int(1), failure=>int(0)` - but I can never get that response.

**Comment by EdwinHoksberg** [comment]
Hi @rolinger, it could be that Google changed the output. Because I don't actually use this package a lot could you create a merge request to change the documentation? Thanks!

**Comment by rolinger** [comment]
@EdwinHoksberg I am rereading FCM documentation this morning.  It turns out your documentation on expected responses is not wrong - there are multiple types of responses based on message type.  There are 3 different types of protocols to communicate push notification messages and I am not fully understanding the difference between the three.

> 1.  **HTTP v1 API**  - I don't fully understand this one - this might be client APP direct to FCM server API - not certain though
> 2. **XMPP Server protocol** - I think this is just an xml version of the json oriented protocol.
> 3. **Legacy HTTP Server Protocol** - app server to client app via FCM.  This is whats being used in this fcm-php repository, not certain why they refer to it as `legacy` though


The below are references to the Legacy HTTP Server Protocol 
> 1. Sets up who you are trying to communicate with (IDs, Topics, etc) https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json
> 2.  This defines the message / `notfication` payload (ie: sound,icon, badge, etc):  Notice, there are 2 tables: 2a for iOS and 2b for Android - finding the overlap is probably the better/universal way to go:  https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support 
> 3. The response messages:
>      a.   https://firebase.google.com/docs/cloud-messaging/http-server-ref#interpret-downstream
>      b.   Table 5: `to` or `registration_ids` JSON response (this is whats defined in your documentation
>      c.   Table 6: `topic` JSON response - this is what I am getting when sending messages to my groups
>      d.  Table 7 (Success) & Table 8 (Error) - responses to plain text (non JSON) HTTP messages

Your documentation is right...I just need to add additional documentation for both how to send notifications to a `topic` and for the `topic` responses.

**Comment by rolinger** [comment]
@EdwinHoksberg In our php code, do these needed to be added per platform? - or does FCM just ignore the options in notifications that are/aren't supported by each platform?   Lets add support for all of this - make this repository useful for everyone.

iOS only:
     * badge 
     * subtitle

Android only:
    * tag
    * color (added)
    * android_channel_id
    * icon (added)

Both:
    * title (done)
    * body (done)
    * sound (added)
    * click_action
    * body_loc_key
    * body_loc_args
    * title_loc_key
    * title_loc_args

**Comment by rolinger** [comment]
Added support for all of the following and also updated and clarified the Message docs, you should be able to merge them now.

iOS only:
* badge (added)
* subtitle (added)

Android only:
* tag (added)
* color (added)
* icon (added)

Both:
* title (done)
* body (done)
* sound (added)

**Comment by rolinger** [comment]
closing this thread, opening a new master with all combined.
