### ISSUE TITLE
Add Sound and Vibrate

### ISSUE THREAD

**Issue by malikdoksoz** [EdwinHoksberg/php-fcm#16]
` $request['notification']['default_sound'] = true;
$request['notification']['default_vibrate_timings'] = true;
` `
I recommend that you link it to the library and add optional.
src/Push/Notification.php

**Comment by rolinger** [comment]
@malikdoksoz - use my fork, I have added many options that are not supported in the original project - including sound.  I think we will be splitting my fork out as its own project because the original @EdwinHoksberg project owner is no longer supporting this main project.  Stay tuned.

**Comment by rolinger** [comment]
@malikdoksoz - sound has been added and vibrate is supported if you are sending data payload.

#closing.
