### ISSUE TITLE
Fatal Error if tokenID is not found using \Fcm\Device\Info

### ISSUE THREAD

**Issue by rolinger** [EdwinHoksberg/php-fcm#17]
When retrieving existing device info about a tokenID/deviceID, if the token does not exist Google returns a `404 Not Found {"error":"No information found about this instance id."}`.  

This is the offending code:

```
  $client = new \Fcm\FcmClient($serverKey,$senderID) ;
  $info = new \Fcm\Device\Info($deviceID, true);
  $response =  $client->send($info);                         // <-----  error below  ----->
  if (array_key_exists('error',$response)) {
    echo "\n\t" .$response['error'] ;
  } else if (array_key_exists('rel',$response)) {  
    foreach ($response['rel']['topics'] as $key => $value) {
      echo "\n\tTopic: $key" ;
    }
  } else {
    echo "\nNo Topics Registered To This ID" ;
  }

```

If the tokenID exists all is good, however, if not found this response causes a Fatal Error:
```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://iid.googleapis.com/iid/info/dk4jUDTwi6E:APA91bFj6R4P6E0RiE5Wc9D267gquYcpKtLjczg-Ok5llCAf_BNbbFp_HyH-r4A5CrxfkCCfIqLx1j4Fc2U9XyFnyrtXBE0WK744wH8dbCz7Wr-kXJxh3ErsQ71ZoEmxbGmCXtJ-yMiS?details=true` resulted in a `404 Not Found` response:
{"error":"No information found about this instance id."}
 in /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/dev/public_html/api/assets/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/dev/public_html/api/assets/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleH in /home/dev/public_html/api/assets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

I have tried various things to fix this but nothing so far has worked.  Though it appears to be a guzzlehttp error, I am hoping someone here could lend a hand in fixing it.

**Comment by rolinger** [comment]
We are restructuring all of our topicIDs and need to retrieve every subscription for every user to first remove them all from each subscription and then subscribe them to the new topicIDs.  But with the above error, we can't script this because the first non-valid tokenID causes guzzlehttp to Fatal Error.

**Comment by rolinger** [comment]
locally, In line 66 of `vendor/guzzlehttp/guzzle/src/Middlewar.php` I changed the function from:

```
                    function (ResponseInterface $response) use ($request, $handler) {
                        $code = $response->getStatusCode();
                        if ($code < 400) {
                            return $response;
                        } 
                        throw RequestException::create($request, $response);
                        }
                    }
```

To this:

```
                    function (ResponseInterface $response) use ($request, $handler) {
                        $code = $response->getStatusCode();
                        if ($code < 400) {
                            return $response;
                        } else if ($code == 404){
                            return $response ;
                        } else {
                          throw RequestException::create($request, $response);
                        }
                    }
```

This by no means is a permanent fix, but it temporarily allows my scripts to keep working.    I think guzzlehttp needs to fix their code or offer a switch of some sort - not all 404 Responses need to be turned into `throw` Fatal Errors.

**Comment by rolinger** [comment]
Update.  it turns out guzzlehttp has an option that can be set to turn off fatal errors for non-responsive pages.  By default, the option to return a fatal error is turned on.  This should be the proper method versus my solution above.    There are several options on how to address this - none of which I have implemented yet.  Google "guzzlehttp disable fatal errors".  One is an option setting but I don't know if this is the best method because you may need this behavior in other packages that rely on guzzlehttp - thus I think an FCM specific code fix (ignoring the fatal error) is the best method to go.

**Comment by AndyGaskell** [comment]
I've been hitting this same issue, I'll have a look and see if I can figure out the guzzlehttp fix.

**Comment by AndyGaskell** [comment]
I think, in the getGuzzleClient function, setting http_errors to false, we can change this to not error, so in...
https://github.com/EdwinHoksberg/php-fcm/blob/d188969e2270856ea48ec773ccca76019c6d4e5a/src/FcmClient.php#L115

We could change it from...
```
    public function getGuzzleClient(): Client
    {
        // Create configuration array
        return new Client([
            'headers' => [
                'Authorization' => 'key='.$this->apiToken,
                'project_id' => $this->senderId,
            ]
        ]);
    }
```
...to...
```
    public function getGuzzleClient(): Client
    {
        // Create configuration array
        return new Client([
            'headers' => [
                'Authorization' => 'key='.$this->apiToken,
                'project_id' => $this->senderId,
            ],
            'http_errors' => false,
        ]);
    }
```

We should have a think if we want this everywhere though. What do you think @rolinger ?

**Comment by rolinger** [comment]
I still have the above fix in my server code...hadn't gotten back around to figuring out the best solution.  Been hard at work revamping the billing system for our platform - its quite complicated with too many billing permutations/combinations.  Been buried in it for last few weeks now.

On a side note, aside from tracking each app instance to see if a user has enabled/disabled push notifications - are you aware of any other method via FCM that tells if you "if subscribed topic members have disabled push notifications" ?  

When user downloads our app we auto-subscribe them to specific FCM topics.  But if the user disables push notifications (Phone Settings Notifications) does that somehow alert FCM to not sent notifications to that deviceID?  Or does the deviceID still stay subscribed to the topic but at the phone level its blocking the inbound notifications?  

It actually makes a big difference in how this is done.  If disabling notifications tells Google FCM NOT to send notifications, then technically we could query FCM to see which deviceIDs have opted out and use that info to maybe send a text message or email - some way of still notifying the user of some info.  If not, then we have to rely on the user starting up the app to determine if they are still enabled or disabled and then update our DB so that when we send a push notification then send a secondary message (text/email) to all users who we have recorded as disabled.  The problem with this one though is if they have disabled notifications AND haven't used the app in a while - we won't get their current status - and then that user isn't getting the message through the alternative methods.

**Comment by rolinger** [comment]
@AndyGaskell - Nice, a clean method.  yeah, I like that.  Maybe make the `'http_errors' => false,` an option parameter in our code.  Something like:

At the client method: ` $client = new \Fcm\FcmClient($apiToken, $senderId, "true/false");`

Or at the Device\Info method: 
```
// Remove the second parameter for more basic device information
//3rd parameter as http-error - well prob need to make it 2nd parameter (required) and then move current 2nd parameter to 3rd parameter so it stays optional.
$info = new \Fcm\Device\Info($deviceId, true, true/false);
```

**Comment by AndyGaskell** [comment]
yea, billing systems are hard, and people seem to get upset if they get it wrong, can't think why though :) 

Yea, we've been facing some similar questions.

I'm not sure about if the user doesn't accept push permissions, I'll maybe give it a try.  I like the idea of checking if they have a subscription, and if not, sending them a SMS message.

Are you using Cordoba?  Just out of curiosity, it's all the same I guess. We're using Flutter at the moment.

The things I've been wondering is...
# How long does FCM leave it before removing subscriptions for inactive devices?
# Does the subscription get removed if the app is uninstalled

**Comment by AndyGaskell** [comment]
They should have threads in Github issues, that always confuses me, replies out of sync.

The `getGuzzleClient` function is called in the `send` function, so it's be easier to have this option/parameter in the `send` function.
 
So, we could add a second optional parameter to the `send` function, and then add an optional parameter to the `getGuzzleClient` function.

It's probably simpler to explain in code, so will do a PR, just as an idea.

**Comment by rolinger** [comment]
We are using Cordova/Ionic.

If the deviceID is not longer valid FCM removes it from any/all subscriptions in real time.  We already experienced this...our DB had old deviceIDs (thus the user has not used the app in a while which would auto-refresh the deviceID in our DB).  Thus when we went to pull deviceID info for subscribed topics we got a "badID" (which in turn caused the above `\Device\Info` guzzlehttp error.  

I don't know if the user uninstalls the app though.  I would imagine FCM removes the deviceID from the topic.  

We capture deviceID, user phone number and user email address during app registration.  I don't like the fact the deviceIDs can expire/change randomly - doesn't make sense as to why this would happen.  One would think Google FCM would tie a deviceID to the base user account required to operate an Android OR an iPhone so even if the user got a new phone and reinstalled everything they would retain the same deviceID.  

Phone and deviceID are verified at registration time...we send a verify email to the users email but we hardly ever get a response from those emails.  So to combat that we auto validate the email by marking it as valid upon registration - then if the verify email bounces back we know its bad then go back into DB and mark users email as invalid.  Phone number is always valid, but like push notifications though could opt out of receiving text messages then we have to rely on email.

We have a system in place that first does a push notification, if we know user has disabled push send text, if disabled text then send email.

**Comment by rolinger** [comment]
RE guzzlehttp - I get what you are saying...have it hard set to `false` with option to re-enable from the `send` function.

**Comment by AndyGaskell** [comment]
Hmm, just trying that, but need to have a think more about error handling.

So it works nicely, with no guzzle error, but then you end up getting a json decode error in the `send` function instead, like...

```
PHP Fatal error:  Uncaught Fcm\Exception\FcmClientException: Failed to json decode response body: Syntax error in /var/www/html/piota/backends/core/cli/vendor/edwinhoksberg/php-fcm/src/FcmClient.php:78
Stack trace:
#0 /var/www/html/core/cli/fcm_test.php(202): Fcm\FcmClient->send(Object(Fcm\Device\Info), false)
#1 {main}
  thrown in /var/www/html/core/cli/vendor/edwinhoksberg/php-fcm/src/FcmClient.php on line 78
```
...which makes sense, as it assumes `getUrl` will come back with good json.

Thanks for the details on your system design, that's really interesting to know.  We're only been using FCM for a couple of months, so have not hit some of these issues yet.

**Comment by rolinger** [comment]
I am not impressed with Google FCM implementation.  It is very limited - and considering its Google, that strikes me as really odd.

**Comment by AndyGaskell** [comment]
Hopefully this is fixed by...
potential solution for guzzle options #31

**Comment by AndyGaskell** [comment]
A fix for this is now in the code.

See https://php-fcm.readthedocs.io/en/latest/packageoptions.html
