### ISSUE TITLE
question : how to broadcast ?

### ISSUE THREAD

**Issue by titoff002** [EdwinHoksberg/php-fcm#18]
Hello,

In your example below: what is the variable `$deviceId` ?

How should we initialize it?

How to send a message to all the people who accepted the fcm notification? (do a broadcast).

Thank you for your work.

**Comment by rolinger** [comment]
@titoff002 - $deviceId is the unquie FCM tokenID each device/phone is assigned by Google.  You register deviceID/tokenIDs to a topic, then you send a message to that topic and that message is then broadcast to all users (deviceID/tokenIDs) that are registered to that topic.

**Comment by rolinger** [comment]
@titoff002  - also, use my fork, it has more FCM options now and is better documented.

**Comment by rolinger** [comment]
No response, closing.
