### ISSUE TITLE
Fatal error on implement Fcm\Request

### ISSUE THREAD

**Issue by MagroGaming** [EdwinHoksberg/php-fcm#19]
Dear developer,

I'm getting an PHP fatal error on the Notification class.
It seems an easy fix, but I wasn't sure because you should've seen the same error as i'm seeing right now:

PHP Fatal error:  Class Fcm\Push\Notification contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Fcm\Request::getUrl) in ***/vendor/edwinhoksberg/php-fcm/src/Push/Notification.php on line 8

I don't see the implementation in the Notification class, I do see it in the Data and Push class...
Could you clarify for me please?

**Comment by rolinger** [comment]
@MagroGaming - did you get this resolved?  Post your code.  Also, you should be using my fork as there are many fixes, additions and better support documentation in my fork.  We should be splitting my fork out as its own project soon as this original project is no longer supported by its creator.

**Comment by rolinger** [comment]
@MagroGaming - we just made a bunch of fixes and merged the new build.  Try retesting now.

**Comment by AndyGaskell** [comment]
I think we can close this now.

@MagroGaming please re-open it if you're still having this issue
