### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by mhd-yasser-haddad** [EdwinHoksberg/php-fcm#22]
I tested and tried the notification on the local server and everything was going fine and the notification was sent successfully, but when I uploaded the project to the server (windows server) the function would give me 500 internal server error on the send function.
Could you please help me?
thank you in advance

**Comment by rolinger** [comment]
@mhd-yasser-haddad - you will need to post a bit more info.  What is your config...what are your paths to the php-fcm project, etc?  What is your script referencing? etc.

**Comment by mhd-yasser-haddad** [comment]
so I have this function inside a class that sends the notification:
//////////////////////////////
/////////////////////////////
public static function sendNotification($title, $body, $deviceToken, $data)
    {

        // Instantiate the client with the project api_token and sender_id.
        $client = new \Fcm\FcmClient(SELF::$serverKey, SELF::$senderId);

        // Instantiate the push notification request object.
        $notification = new \Fcm\Push\Notification();

        $notification
            ->addRecipient($deviceToken)
            ->setTitle($title)
            ->setBody($body);
        foreach ($data as $key => $value)
            $notification->addData($key, $value);

        // Send the notification to the Firebase servers for further handling.
        $response = $client->send($notification);
        return $response;
    }
//////////////////////////////
/////////////////////////////
I ran this code on my localhost and everything was going well, then I uploaded the code to the server and it stopped working and it kept giving me (500 internal server error).
Note that I tried to put echo and die statements in this code and everything was fine before the 
"$response = $client->send($notification);"
and when I put it after this statement in got me an internal server error.

Thank you in advance

**Comment by rolinger** [comment]
@mhd-yasser-haddad  - Internal server error 500 typically means your code has errored out.  Go to the folder with the script in it and check the `error_log` to see if there is anything telling  you whats wrong.  If you don't see anything try a manual execution of the file from the command line and check error_log again.  I suspect your paths to the FCM-PHP are not correct.

**Comment by mhd-yasser-haddad** [comment]
I tried to look for the error log file but I was unable to locate it, But I tried to use and call this function on the local server and everything ran okay, and I think that if the problem was from the directories the initialise of the $client and $notification variable wouldn't work out? don't you think?

**Comment by rolinger** [comment]
unless you post actual technical stuff, not certain there is much anyone can do assist you.

**Comment by mhd-yasser-haddad** [comment]
It turns out that the problem was from the server ports and IP because there are specific ports that the firebase need to use to send notifications from.
Thank you for your help.
Here are the links that helped discover the problem:
https://firebase.google.com/docs/cloud-messaging/concept-options
https://support.fitnessondemand247.com/hc/en-us/articles/360007883114-Firewall-and-Network-Port-Rules
