### ISSUE TITLE
411 Length Required when sending push notifications

### ISSUE THREAD

**Issue by bimbo1989** [EdwinHoksberg/php-fcm#24]
Hi, I'm using this very simple code to send the notifications

```php
// Instantiate the client with the project api_token and sender_id.
$client = new \Fcm\FcmClient($api_token, $sender_id);

// Instantiate the push notification request object.
$notification = new \Fcm\Push\Notification();

// Enhance the notification object with our custom options.
$notification
    ->setTitle($my_title)
    ->setBody($my_message);

$notification->addTopic($my_topic); 

// Send the notification to the Firebase servers for further handling.
$client->send($notification);
```

But I'm getting a 411 error in response when sending. How can I set the Content-Length, appearently required?
Thank you!

**Comment by rolinger** [comment]
@bimbo1989 - interesting.  Will look into this and get back.  Currently header `Content-Length:` is not an option that can be set.  But also not certain why you are getting it either.  No one else has reported this and I have not seen this issue or error before.

**Comment by rolinger** [comment]
@bimbo1989 - can you post your `$my_title` and `$my_message` values you are testing with?

`Check that the total size of the payload data included in a message does not exceed FCM limits: 4096 bytes for most messages, or 2048 bytes in the case of messages to topics. This includes both the keys and the values.`

**Comment by rolinger** [comment]
@bimbo1989 - upon further review it looks like you are mixing methods.

`addTopic` does not exist.  Not even for subscribing to a new topic.  

To send an actual notification it would be:
```
    $notification
        ->addRecipient('/topics/' .$my_topic)
        ->setTitle($subject)
        ->setBody($msg)
        ->setSound("default")
        ->setColor($customColor)
        ->setIcon("notification_icon") ;
```

**Comment by bimbo1989** [comment]
@rolinger ok, I removed the addTopic and replaced it with addRecipient as you suggested (sorry for that mistake) but unluckily I still get the same 411.
This is a print_r of the $notification variable before sending it.

```
Fcm\Push\Notification Object
(
    [title:Fcm\Push\Notification:private] => Notifiche push
    [body:Fcm\Push\Notification:private] => Benvenuto!
    [recipients:Fcm\Push\Notification:private] => Array
        (
            [0] => /topics/my_topic_name
        )

    [topics:Fcm\Push\Notification:private] => Array
        (
        )

    [data:Fcm\Push\Notification:private] => Array
        (
        )

)

```

Do I need to add something else?

**Comment by rolinger** [comment]
@bimbo1989 Please post the $response from `$client->send($notification) ;`

@AndyGaskell - you have any thoughts on this one?

**Comment by bimbo1989** [comment]
It might be interesting to add that everything was working fine while in localhost, using the web API key.
Then I deployed to production and... 411. First I had a different error because I was still using the Web API key, the 411 began to appear when I used the Cloud Messaging server key.
Did I do something wrong there? I'm sure it's not your fault, I must be doing something very stupid being a newbie when it comes to Firebase 😅

**Comment by bimbo1989** [comment]
@rolinger I get no $response because the exception gets thrown before getting the response from the server

**Comment by rolinger** [comment]
Are you trying:
`$reponse = $client->send($notificaiton) ;`

The error would then be like: `$response['results'][0]['error']` 

Well, its def not my fault, because mine works just fine.  :-)   However, if you had it working with localhost, then my guess is you have something else going on.  Verify your serverID and tokenIDs - and that your production server (domain) is allowed to use those keys.

**Comment by bimbo1989** [comment]
@rolinger  no $response either because the exception is thrown inside send() so it does not return anything. I'll try and check the IDs and let you know

**Comment by bimbo1989** [comment]
@rolinger I solved!
I just generated a new server key and it worked flawlessly. The weird thing is that the new one has no differences compared to the first. Oh well!
I'm really sorry for wasting your time, but I hope that this thread might help someone in the future :)
