### ISSUE TITLE
Documentation not consistent with composer package

### ISSUE THREAD

**Issue by VincentNikkelen** [EdwinHoksberg/php-fcm#25]
Hi,

I just started evaluating your component and discovered an issue that might put off less experienced users.

Documentation recommends installation with composer, but the first Notification example is using methods like setColor, setSound and setIcon which are not available in the composer package.

May I recommend to create a new release to bring the code downloaded by composer in line with the documentation.

Thank you in advance.

update: alternatively, documentation could as well mention using composer with a specific git hash.

**Comment by AndyGaskell** [comment]
Thanks for raising this @VincentNikkelen 

From looking at...
https://packagist.org/packages/edwinhoksberg/php-fcm
...it seems to be using 1.0.0 by default, which is from 2018-04-09.

I'll have a look and see about updating it in Packagist to use dev-master.

**Comment by AndyGaskell** [comment]
Just adding a tag with...
`git clone git@github.com:EdwinHoksberg/php-fcm.git
cd php-fcm
git tag 1.1.0
git push origin 1.1.0`
...then setting it to release at https://github.com/EdwinHoksberg/php-fcm/tags

**Comment by AndyGaskell** [comment]
I made a release of the latest dev-master, from the 1.1.0 tag at https://github.com/EdwinHoksberg/php-fcm/releases

**Comment by AndyGaskell** [comment]
Now v1.1.0 seems to be the default version on packagist, so composer should pick that up.

https://packagist.org/packages/edwinhoksberg/php-fcm

**Comment by AndyGaskell** [comment]
Doing a quick test of...
`composer require edwinhoksberg/php-fcm`
...it gives the output with the new 1.1.0 release...

Using version ^1.1 for edwinhoksberg/php-fcm
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing symfony/polyfill-php72 (v1.18.0): Downloading (100%)         
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing symfony/polyfill-php70 (v1.18.0): Downloading (100%)         
  - Installing symfony/polyfill-intl-normalizer (v1.18.0): Downloading (100%)         
  - Installing symfony/polyfill-intl-idn (v1.18.0): Downloading (100%)         
  - Installing guzzlehttp/guzzle (6.5.5): Downloading (100%)         
  - Installing edwinhoksberg/php-fcm (v1.1.0): Downloading (100%)         
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/polyfill-intl-normalizer suggests installing ext-intl (For best performance)
symfony/polyfill-intl-idn suggests installing ext-intl (For best performance)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Writing lock file
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by AndyGaskell** [comment]
If you could test it too @VincentNikkelen that would be really helpful

**Comment by VincentNikkelen** [comment]
@AndyGaskell Works like a charm:
  - Downgrading edwinhoksberg/php-fcm (dev-master d188969 => v1.1.0):  Checking out 772f1f49bd
Wouldn't worry about the downgrading wording, issue in composer.
Thanks.
Btw, can confirm I have decided to use your package in my code. Was easy to use and simply works. Thank you very much.

**Comment by AndyGaskell** [comment]
@VincentNikkelen 
Thanks for checking the fix, and your feedback. Glad it's work well for you 🙂
