### ISSUE TITLE
How to Get sound notifications

### ISSUE THREAD

**Issue by thanhansoft** [EdwinHoksberg/php-fcm#3]
Hi admin,
I want to notification with sound option.
Please help me

**Comment by webrufox** [comment]
Need change code

**Comment by rolinger** [comment]
In fact, need to add a few items like "sound", "icon", "vibrate", etc - https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification

**Comment by rolinger** [comment]
I forked this package and added `notfication` support for `sound`, `color` and `icon` - https://github.com/rolinger/php-fcm  - specifically in `src/Push/Notification.php`

**Comment by rolinger** [comment]
`sound` is now supported.

#closing.
