### ISSUE TITLE
Guzzle option, made a bit of a mess of the commit / merge

### ISSUE THREAD

**Issue by AndyGaskell** [EdwinHoksberg/php-fcm#32]
Hi @rolinger 

Sorry, I made a bit of a mess of the Guzzle option changes, so thought I'd best jot some notes to explain.

I think the code, docs and tests are all ok, but I accidentally merged directly into the master, rather than into my branch and then making a PR.

This is related to...

-  Revert "added Guzzle options to prevent PHP fatal error" #27 
-  added Guzzle options to prevent PHP fatal error #26 
-  Fatal Error if tokenID is not found using \Fcm\Device\Info #17 
-  Fatal error on implement Fcm\Request #19 

So just writing an issue to explain, and to tie all the other threads about this together.

**Comment by rolinger** [comment]
@AndyGaskell - uh, you assigned this to me.  Assigned what specifically? Do I need to revert something?

**Comment by AndyGaskell** [comment]
Hi @rolinger 
Sorry, no, nothing to do really, just wrote this up as an issue to explain what had happened with the merge.
I guess my reason for assigning it to you was so you'd be aware of it all and could check it looks OK.  As I accidentally just merged it into master there was no PR to review.
If it looks ok, code and docs, just close this.  Sorry it's not done properly with a PR.
