### ISSUE TITLE
LUMEN/LARAVEL

### ISSUE THREAD

**Issue by arashifunsho** [EdwinHoksberg/php-fcm#4]
So, this is not really an issue per se; I want to know if i can use this as is within Lumen or Laravel or I need some adjustments.

Apart from this, this is a really nice package to have. Kudos!

**Comment by arashifunsho** [comment]
So I've decided to give it a shot and revert. Will do that.

**Comment by EdwinHoksberg** [comment]
Hi! Yes this package can be used in combination with laravel or lumen. There's no service provider but it should work fine if you follow the documentation :)

**Comment by arashifunsho** [comment]
Yea... I noticed that.

I also noticed that I can't send DATA and NOTIFICATION in the same payload(I checked the source/docs, correct me if I'm wrong); it's one of the two not both
