### ISSUE TITLE
Tag a new version for Guzzle 7

### ISSUE THREAD

**Issue by shaffe-fr** [EdwinHoksberg/php-fcm#41]
Hi,
Would it be possible to tag a new version to make the Guzzle 7 support available in composer?
Thanks

**Comment by bluelupin** [comment]
It would be great if it could support Guzzle 7.2.
Not able to use it with Laravel 8.*

**Comment by shaffe-fr** [comment]
Same here. By the way, I try to use the latest master on Laravel 8 and it's working great.

**Comment by AndyGaskell** [comment]
ok, I'll have a look

**Comment by AndyGaskell** [comment]
I created a new release tag from master, 1.2.0

I had to tweak a couple of travis bits, but that was ok I think

It seems to have updated at https://packagist.org/packages/edwinhoksberg/php-fcm

@shaffe-fr and @bluelupin does this look ok?

**Comment by shaffe-fr** [comment]
Works perfectly, thanks!
