### ISSUE TITLE
Priority settings missing?

### ISSUE THREAD

**Issue by lukasza67** [EdwinHoksberg/php-fcm#48]
Hello and thanks for a great work!

I have been going through the documentation and it seams that there is no way of setting the message priority for the notification. As it is now it sends with no settings and it gets "normal" priority by default at FCM-level. Or did I miss to set it manually somewhere?

I think this is a very important feature as on battery saving mode or locked screen the notification is now delayed until the user becomes active with the display.

**Comment by lukasza67** [comment]
So I've solved the issue by doing the following quick fix: 

In the end of Push/Notification->getBody() I simply added:
```php
$request['priority'] = "high";
```

This made my notifications go in warp speed no matter of the devices state (I used cordova).

![image](https://user-images.githubusercontent.com/25504901/114754827-ad4faa80-9d61-11eb-887f-a516c905298d.png)

Also for housekeeping purposes :smiley:

**Comment by AndyGaskell** [comment]
Hi @lukasza67 
That's really useful to know, thanks, I didn't realised normal priority push messages were treated that way.  I'll have a look at writing a getter and setter for this.
Re getBody v setBody, I see what you mean, if we can't fix this in a non breaking way we can adjust the docs to better explain it.

**Comment by Philipp91** [comment]
> Re getBody v setBody, I see what you mean, if we can't fix this in a non breaking way we can adjust the docs to better explain it.

How about renaming getBody() to buildJsonRequest() and leaving behind a deprecated getBody() that just redirects and will be removed in the next major release?

**Comment by Philipp91** [comment]
I'd also need the priority. I believe I could put together a PR if that helps.
