### ISSUE TITLE
Sending messages to subscription topics

### ISSUE THREAD

**Issue by rolinger** [EdwinHoksberg/php-fcm#5]
Hi, I just discovered this php-fcm package.  Looks slick and clean and I will be replacing my custom code with this - so much easier to use.  Thx.

Question though - using php-fcm how do you send messages to a subscription topic?  I have thousands of users subscribed to a various topics, but I see no way to send messages to a particular topic?  Your documentation shows how to subscribe/unsubscribe devices from particular topics - but not now to send messages to those topics.

Referencing: https://firebase.google.com/docs/cloud-messaging/js/topic-messaging#build_send_requests

**Comment by EdwinHoksberg** [comment]
Hi! According to [this](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json) link you can send a message to a topic like this: `/topic/$topicName` as the value for `addRecipient` function. 

Example:
```php
$notification
    ->addRecipient('/topic/my-topic-name')
    ->setTitle('Hello from php-fcm!')
    ->setBody('Notification body');

$client->send($notification);
```

Unfortunately I don't have time to test this now but maybe it works like that :)
