### ISSUE TITLE
Missing collapse key

### ISSUE THREAD

**Issue by Philipp91** [EdwinHoksberg/php-fcm#57]
See docs: https://firebase.google.com/docs/cloud-messaging/concept-options#delivery-options

And another PHP implementation: https://github.com/Paragraph1/php-fcm/blob/b8d6fec2c5327ed8fbe09d4d1cc0b53467a340e0/src/Message.php#L151

**Comment by AndyGaskell** [comment]
Thanks @Philipp91 I'll try and implement that.  

I've not seen Paragraph1/php-fcm so that's handy to see how they've implemented things.

**Comment by Philipp91** [comment]
Thanks. If you prefer, I can also take a stab at it. Btw, is this repository still maintained? I haven't seen a reaction to my (unrelated) PR, there are several PRs open for a while, and @EdwinHoksberg hasn't been active on GitHub for a while.

@EdwinHoksberg This may just be a coincidence (like vacation week or sth like that), in which case please disregard my comment. Though if you find yourself being less active on GitHub for whatever reasons, please consider giving @AndyGaskell or someone else who contributes a lot enough write access to this repository to allow merging PRs -- not sure about releases.

**Comment by AndyGaskell** [comment]
Hi @Philipp91 
Although Edwin created this project originally, he did not have time to maintain it really.  So a couple of years ago he gave admin access to me and @rolinger.  
While we try to keep on top of things, time commitment is always a bit of a juggling act.  I need to set aside a couple of days to catch up on issues and PRs.  Some parts of the project are not in my core skill set, like the type of unit testing we use, or Laravel conventions.  
Any help would be greatly appreciated though :)

**Comment by rolinger** [comment]
@AndyGaskell - heh....`set aside a couple of dsays to catch up on issues`.  I wish I just had a couple of hours.  I try to keep up with this repo and I know advances have been made with it and how push notifications work in general - none of which I have had time to incorporate into my projects.  Ugh.
