### ISSUE TITLE
Class fcm\fcmclient not found 

### ISSUE THREAD

**Issue by rolinger** [EdwinHoksberg/php-fcm#6]
Getting this error:  Fatal error: Uncaught Error: Class 'Fcm\FcmClient' not found 

My install:
```
 composer require edwinhoksberg/php-fcm
Using version ^1.0 for edwinhoksberg/php-fcm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

And my script:
$senderID = "2...........9" ;
$serverKey = "AAAAMjf9F3s:APA91bEjl4MJ............VwvqxrC0fIkH8G" ;
$response = $client = new \Fcm\FcmClient($serverKey,$senderID) ;

I even tried adding: `use Fcm\FcmClient ;`

But still get same error, `class not found`

**Comment by EdwinHoksberg** [comment]
Hello, is that your full script you pasted there? Because you didn't include the composer file, try adding this line on top of your file: 
```php
require 'vendor/autoload.php';
```
Make sure the path is correct relative to your script file!

**Comment by rolinger** [comment]
Thanks.  That did the trick.  Maybe that needs to be included in the documentation.  I was trying to use `use Fcm\FcmClient;` or `include Fcm\FcmClient` thinking that would be the path to the class.

**Comment by rolinger** [comment]
closed.

**Comment by OmkarFatale** [comment]
I'm having the same issues, I have included "require 'vendor/autoload.php'" at top.
<?php
// Load composer
require 'vendor/autoload.php';

$server_key = "AAAAfAxtccc:************41";

$sender_ID = "532************";

$client = new \Fcm\FcmClient($server_key, $sender_ID);

var_dump($client);

Errors: 

Fatal error: Uncaught Error: Class 'Fcm\FcmClient' not found in C:\wamp64\www\php-fcm\php-fcm.php on line 10

Fatal error: Uncaught Error: Class 'Fcm\FcmClient' not found in C:\wamp64\www\php-fcm\php-fcm.php on line 10
