### ISSUE TITLE
Cloud Messaging API (Legacy) Deprecated

### ISSUE THREAD

**Issue by rashtell** [EdwinHoksberg/php-fcm#61]
The legacy authentication way of using `Authorization: key=AIzaSyZ-1u...0GBYzPu7Udno5aA` has been deprecated in favor of `Authorization: Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA`
The payload structure and URLs are also affected.

**Comment by AndyGaskell** [comment]
Thanks for adding this issue, I think this should be covered under the work required for...
 FCM: Migrate from legacy HTTP to HTTP v1 #23
