### ISSUE TITLE
add Badge

### ISSUE THREAD

**Issue by webrufox** [EdwinHoksberg/php-fcm#9]
namespace Fcm\Push;

use Fcm\Exception\NotificationException;
use Fcm\Request;

class Notification implements Request
{
...
modify function 
...
public function __construct(string $title = '', string $body = '', string $recipient = '', int $badge = 0)
{
        $this->badge = $badge;
.....
}

....
add function
....

    /**
     * @param int $badge
     *
     * @return $this
     */
    public function setBadge(int $badge): self
    {
        $this->badge = $badge;

        return $this;
    }

....
modify function
....

    public function getBody(): array
    {
....
        if ($this->badge>0) {
	        $request['notification']['badge'] = $this->badge;
	    }

        return $request;
    }
}

**Comment by rolinger** [comment]
`sound` and `icon` too - and probably the rest of these: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification

**Comment by rolinger** [comment]
@webrufox - is `badge` even used anymore?  I couldn't find it in the docs above.

However, I forked this package and added `notfication` support for `sound`, `color` and `icon` - https://github.com/rolinger/php-fcm  - specifically in `src/Push/Notification.php`

@EdwinHoksberg - maybe you could merge my fork back to the main package.

**Comment by EdwinHoksberg** [comment]
Hi @rolinger, looks great! If you can send me a merge request I'd happily merge it.

**Comment by rolinger** [comment]
@EdwinHoksberg Never did a pull request for a merge before - I think I just did one, let me know if I didn't do it right.

**Comment by rolinger** [comment]
Support for badge, and MUCH more, has been added to my fork `rolinger/php-fcm` - @EdwinHoksberg just needs to merge my pull request.

**Comment by rolinger** [comment]
`badge` support has been  added.  

#closing.
